# Generated by Django 2.2.1 on 2019-05-13 07:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('upload_date', models.DateTimeField(default=datetime.datetime(2019, 5, 13, 7, 9, 43, 453447, tzinfo=utc), verbose_name='Date of upload')),
                ('content', models.TextField()),
            ],
        ),
    ]
