# Generated by Django 2.2.1 on 2019-05-13 07:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0004_auto_20190513_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 7, 22, 57, 667898, tzinfo=utc), verbose_name='Date of upload'),
        ),
    ]
