# Generated by Django 2.2.1 on 2019-05-14 14:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0013_auto_20190513_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 14, 23, 14, 501669, tzinfo=utc), verbose_name='Date of upload'),
        ),
    ]
