# Generated by Django 2.2.1 on 2019-05-14 15:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0014_auto_20190514_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 15, 6, 44, 711283, tzinfo=utc), verbose_name='Date of upload'),
        ),
    ]
