# Generated by Django 2.2.1 on 2019-05-15 13:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0015_auto_20190514_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 13, 1, 38, 518881, tzinfo=utc), verbose_name='Date of upload'),
        ),
    ]
